message:
  in_progress: "Пожалуйста подождите"
  invalid: "Неверный формат запроса"
  success: "Все получилось"
  error: "Произошла ошибка, попробуйте позже"
  all_error: "Сервис временно не работает"