spring:
  config:
    import: optional:configserver:http://localhost:8888/config-server/config
  datasource:
    hikari:
      maximum-pool-size: 15
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
  liquibase:
    enabled: true
datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: admin@123
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect