server:
  port: "8888"
  servlet:
    context-path: /config-server


spring:
  profiles:
    active: native
  application:
     name: config-server
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:/configs
          prefix: /config